name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:unstable

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y at-spi2-core dbus-x11 gnome-common libbamf3-dev libcairo2-dev libdbusmenu-gtk3-dev libgdk-pixbuf2.0-dev libgee-0.8-dev libglib2.0-dev libgnome-menu-3-dev libgtk-3-dev libwnck-3-dev libx11-dev libxml2-utils meson valac xvfb
    - name: Build
      run: |
        meson -Denable-headless-tests=true build
        ninja -C build
        ninja -C build test
        ninja -C build install
